const API_CONFIGS = {
  groq: {
    endpoint: 'https://api.groq.com/openai/v1/chat/completions',
    model: 'llama-3.3-70b-versatile',
    buildBody: (prompt, model) => JSON.stringify({
      model: model || 'llama-3.3-70b-versatile',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
      max_tokens: 4096
    }),
    buildHeaders: (apiKey) => ({
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    }),
    parseResponse: (data) => data.choices?.[0]?.message?.content
  },
  openai: {
    endpoint: 'https://api.openai.com/v1/chat/completions',
    model: 'gpt-4o-mini',
    buildBody: (prompt, model) => JSON.stringify({
      model: model || 'gpt-4o-mini',
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
      max_tokens: 4096
    }),
    buildHeaders: (apiKey) => ({
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${apiKey}`
    }),
    parseResponse: (data) => data.choices?.[0]?.message?.content
  },
  gemini: {
    endpoint: 'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent',
    model: 'gemini-2.5-flash',
    buildBody: (prompt) => JSON.stringify({
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: { temperature: 0.3, maxOutputTokens: 4096 }
    }),
    buildHeaders: (apiKey) => ({
      'Content-Type': 'application/json',
      'x-goog-api-key': apiKey
    }),
    parseResponse: (data) => data.candidates?.[0]?.content?.parts?.[0]?.text,
    buildUrl: (apiKey) => `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`
  },
  anthropic: {
    endpoint: 'https://api.anthropic.com/v1/messages',
    model: 'claude-haiku-20240307',
    buildBody: (prompt, model) => JSON.stringify({
      model: model || 'claude-haiku-20240307',
      max_tokens: 4096,
      messages: [{ role: 'user', content: prompt }]
    }),
    buildHeaders: (apiKey) => ({
      'Content-Type': 'application/json',
      'x-api-key': apiKey,
      'anthropic-version': '2023-06-01'
    }),
    parseResponse: (data) => data.content?.[0]?.text
  }
};

function buildPrompt(chatContent) {
  return `You are an AI summarizer for long conversations between a user and an AI.
Read the following conversation and create a comprehensive structured summary.

CONVERSATION:
---
${chatContent}
---

Create a summary in the following Markdown format (MUST follow this format EXACTLY):

# Chat Summary — ${new Date().toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' })}

## 🗂️ Main Topics
- [topic 1]
- [topic 2]
- [etc, max 5 points]

## ✅ Decisions Made
- [concrete decisions that were agreed upon]

## ⏳ Unresolved / Needs Follow-up
- [unsolved problems]

## 🧩 Important Context
- **Tech stack:** [languages, frameworks, tools used]
- **Project name:** [project name if any]
- **Environment:** [OS, version, important configs]
- **Preferences:** [coding style, approaches, etc]

## 📌 Prompt for New Chat
"[Write 2-3 concise sentences summarizing the main context to continue in a new chat]"

---
*Summarized by ky-summarizer*

IMPORTANT RULES:
- Answer in the SAME LANGUAGE as the conversation above
- If there are important code snippets, include them in code blocks
- Do not add information that is not in the conversation
- Focus on the MOST USEFUL information for continuing the session`;
}

async function loadSettings() {
  return new Promise((resolve) => {
    chrome.storage.local.get(['provider', 'apiKeys', 'model'], (result) => {
      resolve({
        provider: result.provider || 'groq',
        apiKey: result.apiKeys?.[result.provider || 'groq'] || '',
        model: result.model || null
      });
    });
  });
}

async function callAI(provider, apiKey, prompt, model) {
  const config = API_CONFIGS[provider];
  if (!config) throw new Error(`Unknown provider: ${provider}`);

  const url = config.buildUrl ? config.buildUrl(apiKey) : config.endpoint;
  const headers = config.buildHeaders(apiKey);
  const body = config.buildBody(prompt, model);

  const response = await fetch(url, {
    method: 'POST',
    headers,
    body
  });

  if (!response.ok) {
    const errorText = await response.text();
    let errorMsg = `HTTP ${response.status}`;
    try {
      const errorJson = JSON.parse(errorText);
      errorMsg = errorJson.error?.message || errorJson.message || errorMsg;
    } catch (e) {}
    throw new Error(`API Error: ${errorMsg}`);
  }

  const data = await response.json();
  const content = config.parseResponse(data);

  if (!content) {
    throw new Error('No response from AI. Check your API key.');
  }

  return content;
}

function generateMarkdownFile(summary, provider, url, messageCount) {
  const header = `<!-- Generated by ky-summarizer | ${new Date().toISOString()} -->
<!-- Source: ${url} | Messages: ${messageCount} | Provider: ${provider} -->

`;
  return header + summary;
}

async function setState(state, message = '') {
  const summaryState = {
    status: state,
    message: message,
    timestamp: Date.now()
  };
  await chrome.storage.local.set({ summaryState });
  try {
    chrome.runtime.sendMessage({ action: 'stateChanged', summaryState });
  } catch (e) {
    // Ignore error if popup is not active
  }
}

async function handleSummarize(tabId) {
  const { provider, apiKey, model } = await loadSettings();

  if (!apiKey) {
    await setState('error', 'API Key not set. Click Settings first.');
    return;
  }

  await setState('extracting');

  let extractResult;
  try {
    try {
      await chrome.scripting.executeScript({
        target: { tabId: tabId },
        files: ['content.js']
      });
    } catch (e) {
      console.warn('Script injection warning:', e);
    }

    extractResult = await chrome.tabs.sendMessage(tabId, { action: 'extractChat' });
  } catch (error) {
    await setState('error', `Failed to read page: ${error.message}`);
    return;
  }

  if (!extractResult?.success) {
    await setState('error', extractResult?.error || 'No chat found on this page.');
    return;
  }

  await setState('summarizing');

  let summary;
  try {
    const prompt = buildPrompt(extractResult.rawChat);
    summary = await callAI(provider, apiKey, prompt, model);
  } catch (error) {
    await setState('error', `AI Error: ${error.message}`);
    return;
  }

  await setState('generating');

  const fileContent = generateMarkdownFile(
    summary,
    provider,
    extractResult.url,
    extractResult.messageCount
  );

  const dateStr = new Date().toISOString().slice(0, 10);
  const timeStr = new Date().toTimeString().slice(0, 8).replace(/:/g, '-');
  const filename = `ky-summary-${dateStr}-${timeStr}.md`;

  const utf8Bytes = new TextEncoder().encode(fileContent);
  let binary = '';
  for (let i = 0; i < utf8Bytes.byteLength; i++) {
    binary += String.fromCharCode(utf8Bytes[i]);
  }
  const dataUrl = `data:text/markdown;charset=utf-8;base64,${btoa(binary)}`;

  try {
    chrome.downloads.download({
      url: dataUrl,
      filename: filename,
      saveAs: true
    }, (downloadId) => {
      if (chrome.runtime.lastError) {
        setState('error', `Download failed: ${chrome.runtime.lastError.message}`);
      } else {
        setState('done', `Downloaded ${filename}! (${extractResult.messageCount} messages)`);
        updateStats();
      }
    });
  } catch (e) {
    setState('error', `Download error: ${e.message}`);
  }
}

function updateStats() {
  chrome.storage.local.get(['totalSummarized'], (result) => {
    const total = (result.totalSummarized || 0) + 1;
    chrome.storage.local.set({ totalSummarized: total });
  });
}

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === 'startSummarize') {
    handleSummarize(request.tabId);
  }
});
